Repository Ureca-2th-FE-Matdori/Matdori-frontend, pull requests merged in 2025-05, with the labels that each got.

#2 프로젝트 초기 설정
  .eslintrc.cjs
  .husky/commit-msg
  .prettierrc.json
  commitlint.config.cjs
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/index.css
  src/main.tsx
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: Configuration

#4 라우터 설정 및 폴더 구조 세팅
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/AppRouter.tsx
  src/apis/apis.txt
  src/components/components.txt
  src/constants/path.ts
  src/hooks/hooks.txt
  src/main.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/stores/stores.txt
  src/types/types.txt
  src/utils/utils.txt
Labels: Configuration

#8 feat: 로그인 회원가입 login-input UI 구현
  src/App.tsx
  src/components/common/logininput/loginInput.style.ts
  src/components/common/logininput/loginInput.tsx
Labels: Feat

#12 로그인 화면 및 기능 구현
  src/App.tsx
  src/AppRouter.tsx
  src/apis/apis.txt
  src/apis/authHttp.ts
  src/assets/loginBackground.png
  src/components/common/logininput/loginInput.tsx
  src/constants/path.ts
  src/index.css
  src/main.tsx
  src/pages/LoginPage/LoginPage.style.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/SignupPage/SignupPage.tsx
  src/stores/index.ts
  src/stores/userSlice.ts
  src/types/Login.ts
Labels: Feat

#13 랜딩 페이지 제작
  package-lock.json
  package.json
  src/App.css
  src/components/LandingPage/AnimatedLogo.tsx
  src/components/components.txt
  src/index.css
  src/pages/LandingPage/LandingPage.style.ts
  src/pages/LandingPage/LandingPage.tsx
Labels: Feat

#20 뽑기 창 선택하기 페이지 UI 작성
  package-lock.json
  package.json
  src/App.tsx
  src/AppRouter.tsx
  src/apis/authHttp.ts
  src/assets/favoritePickup.json
  src/assets/map.json
  src/assets/roulette.json
  src/components/PickupPage/SelectPickupCard.style.ts
  src/components/PickupPage/SelectPickupCard.tsx
  src/components/common/GlobalNavigationBar/GlobalNavigationBar.style.tsx
  src/constants/path.ts
  src/index.css
  src/pages/LoginPage/LoginPage.tsx
  src/pages/PickupPage/PickupPage.tsx
  src/pages/PickupPage/pickupPage.style.ts
Labels: 🌟Feature

#19 공통 응답 형식 기반 API 에러 처리 로직 구현
  src/apis/HttpError.ts
  src/apis/axiosInstance.ts
  src/apis/axiosInterceptors.ts
  src/apis/user/postLogin.ts
  src/apis/user/postSignup.ts
  src/constants/api.ts
  src/pages/LoginPage/LoginPage.style.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/SignupPage/SignupPage.style.ts
  src/pages/SignupPage/SignupPage.tsx
Labels: 🌟Feature

#24 Toast 컴포넌트 구현
  src/App.tsx
  src/assets/success-circle.svg
  src/assets/warning-circle.svg
  src/components/common/Toast/Toast.style.ts
  src/components/common/Toast/Toast.tsx
  src/components/common/ToastContainer/ToastContainer.tsx
  src/hooks/useToast.ts
  src/index.css
  src/pages/LoginPage/LoginPage.tsx
  src/pages/SignupPage/SignupPage.tsx
  src/stores/index.ts
  src/stores/slices/toastSlice.ts
  src/stores/slices/userSlice.ts
Labels: 🌟Feature

#23 랭킹페이지 및 랭킹페이지 컴포넌트 제작
  src/App.css
  src/AppRouter.tsx
  src/apis/ranking/getRanking.ts
  src/assets/first-medal.svg
  src/assets/second-medal.svg
  src/assets/third-medal.svg
  src/components/RankingPage/NameCard.style.tsx
  src/components/RankingPage/NameCard.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/index.css
  src/pages/RankingPage/RankingPage.style.ts
  src/pages/RankingPage/RankingPage.tsx
Labels: 🌟Feature

#25 뽑기 결과창 UI 및 기능 제작
  src/App.tsx
  src/AppRouter.tsx
  src/apis/authHttp.ts
  src/apis/history/postHistory.tsx
  src/assets/fireworks1.json
  src/components/PickupResultPage/ResultInfoBox.style.ts
  src/components/PickupResultPage/ResultInfoBox.tsx
  src/components/VisitHistory/HistoryCardDesktop.tsx
  src/components/VisitHistory/HistoryCardMobile.tsx
  src/components/common/NaverDynamicMap/NaverDynamicMap.tsx
  src/constants/api.ts
  src/constants/category.ts
  src/constants/path.ts
  src/pages/PickupResultPage/PickupResultPage.style.ts
  src/pages/PickupResultPage/PickupResultPage.tsx
Labels: 🌟Feature

#28 방문내역 불러오기 API 연동
  index.html
  src/apis/history/getHistory.ts
  src/apis/history/getLatLngFromAddress.ts
  src/components/VisitHistory/HistoryCardDesktop.tsx
  src/components/VisitHistory/HistoryCardMobile.tsx
  src/constants/api.ts
  src/constants/category.ts
  src/pages/VisitHistoryPage/VisitHistoryPage.tsx
  src/types/VisitHistory.ts
Labels: 🌟Feature, 🔧Fix

#29 뽑기 기능에 필요한 API 및 결과창 기능 구현
  src/AppRouter.tsx
  src/apis/select/getCategory.ts
  src/apis/select/getPrefer.ts
  src/apis/select/getRandom.ts
  src/constants/api.ts
  src/hooks/useCurrentPosition.ts
  src/pages/PickupPage/PickupPage.tsx
  src/pages/PickupResultPage/PickupResultPage.tsx
  src/types/randomApi.ts
  tsconfig.app.json
Labels: 🌟Feature

#33 각 페이지로 이동할 수 있도록 GNB 리팩토링
  src/App.tsx
  src/components/common/GlobalNavigationBar/GlobalNavigationBar.style.tsx
  src/components/common/GlobalNavigationBar/GlobalNavigationBar.tsx
Labels: 🔨Refactor

#34 사용자 권한에 따른 페이지 접근 처리
  src/AppRouter.tsx
  src/constants/path.ts
  src/pages/PickupPage/PickupPage.tsx
  src/pages/PickupResultPage/PickupResultPage.tsx
  src/pages/UnauthorizedPage/UnauthorizedPage.tsx
  src/utils/authLoader.ts
  src/utils/utils.txt
Labels: 🌟Feature

#36 로그아웃/홈 이동 버튼 Modal 추가 및 방문내역 카드 레이아웃 수정
  src/assets/svg/home-icon.svg
  src/assets/svg/logout-icon.svg
  src/components/VisitHistory/HistoryCardDesktop.style.tsx
  src/components/VisitHistory/HistoryCardDesktop.tsx
  src/components/common/GlobalNavigationBar/GlobalNavigationBar.style.tsx
  src/components/common/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/index.css
Labels: 🌟Feature, 🔧Fix

#37 결과창 뽑기 코드 개선
  src/apis/select/getCategory.ts
  src/components/PickupResultPage/ResultInfoBox.tsx
  src/constants/api.ts
  src/pages/PickupResultPage/PickupResultPage.style.ts
  src/pages/PickupResultPage/PickupResultPage.tsx
Labels: 🔨Refactor

#40 랭킹페이지 막대그래프 비율 적용 정상화
  src/components/RankingPage/NameCard.tsx
Labels: 🐛Bug

#41 결과창 반응형 UI 제작
  src/components/PickupResultPage/ResultInfoBox.style.ts
  src/components/PickupResultPage/ResultInfoBox.tsx
  src/pages/PickupResultPage/PickupResultPage.style.ts
  src/pages/PickupResultPage/PickupResultPage.tsx
Labels: 🔨Refactor

#42 랜딩 페이지 및 잘못된 접근 페이지의 모바일 화면 구현
  src/pages/LandingPage/LandingPage.style.ts
  src/pages/LandingPage/LandingPage.tsx
  src/pages/UnauthorizedPage/UnauthorizedPage.tsx
Labels: 🌟Feature
